name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Good job on your first issue! Actually, I don't know if you actually did a good job, as I am just a bot. :/"
        pr-message: 'Thanks for contributing to my site! Every contribution helps!'
